spring:
  profiles:
    include: db
  mvc:
    log-request-details: true

logging:
  level:
    root: WARN
    org.springframework.web: TRACE
    com.dreamsecurity.shopface: TRACE

mybatis:
  mapper-locations: classpath:**/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 60
  type-aliases-package: com.dreamsecurity.shopface

security:
  oauth2:
    resource:
      jwk:
        key-set-uri: https://cognito-idp.ap-northeast-2.amazonaws.com/ap-northeast-2_7k26io4kJ/.well-known/jwks.json
