spring:
  profiles:
    include: db
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.ap-northeast-2.amazonaws.com/ap-northeast-2_7k26io4kJ
          jwk-set-uri: https://cognito-idp.ap-northeast-2.amazonaws.com/ap-northeast-2_7k26io4kJ/.well-known/jwks.json
logging:
  level:
    root: WARN
    org.springframework.web: TRACE
    com.dreamsecurity.shopface: TRACE

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 60
    mapper-locations: classpath:mappers/*.xml