spring:
  datasource:
    url: jdbc:oracle:thin:@sfdb.crqwcwmfknog.ap-northeast-2.rds.amazonaws.com:1521:sfdb
    driver-class-name: oracle.jdbc.OracleDriver
    username: admin
    password: 12345678

